package logic.PMCSN.model;

public class Events {

    // === UTENTI -> LOGIN ===
    public static int ARRIVAL_EVENT_LOGIN = 1;
    //public static int SERVERS_LOGIN = 5;
    public static int SERVERS_LOGIN = 2;
    public static int DROPOUT_EVENT_LOGIN = 1;

    // === UTENTI CHE GIOCANO AD ULTIMATE TEAM -> SERVER DI ACCESSO AD ULTIMATE TEAM ===
    public static int ARRIVAL_EVENT_ULTIMATE_TEAM = 1;
    //public static int SERVERS_ULTIMATE_TEAM = 10;
    public static int SERVERS_ULTIMATE_TEAM = 2;
    public static int DROPOUT_EVENT_ULTIMATE_TEAM = 1;

    // === UTENTI CHE GIOCANO A STAGIONI -> SERVER DI ACCESSO A STAGIONI ===
    public static int ARRIVAL_EVENT_STAGIONI = 1;
    //public static int SERVERS_STAGIONI = 8;
    public static int SERVERS_STAGIONI = 2;
    public static int DROPOUT_EVENT_STAGIONI = 1;
    
    // === UTENTI CHE GIOCANO A PROCLUB -> SERVER DI ACCESSO A PROCLUB ===
    public static int ARRIVAL_EVENT_PRO_CLUB = 1;
    public static int SERVERS_PRO_CLUB = 2;
    public static int DROPOUT_EVENT_PRO_CLUB = 1;
    
    // === UTENTI CHE ESEGUONO IL MATCHMAKING DI ULTIMATE TEAM -> SERVER DI MATCHMAKING DI ULTIMATE TEAM ===
    public static int ARRIVAL_EVENT_MATCHMAKING_UT = 1;
    public static int SERVERS_MATCHMAKING_UT = 2;
    public static int DROPOUT_EVENT_MATCHMAKING_UT = 1;
    
   // === UTENTI CHE ESEGUONO IL MATCHMAKING DI ULTIMATE TEAM -> SERVER DI MATCHMAKING DI STAGIONI ===
    public static int ARRIVAL_EVENT_MATCHMAKING_STAGIONI = 1;
    public static int SERVERS_MATCHMAKING_STAGIONI = 2;
    public static int DROPOUT_EVENT_MATCHMAKING_STAGIONI = 1;
    
 // === UTENTI CHE ESEGUONO IL MATCHMAKING DI ULTIMATE TEAM -> SERVER DI MATCHMAKING DI PRO CLUB ===
    public static int ARRIVAL_EVENT_MATCHMAKING_PRO_CLUB = 1;
    public static int SERVERS_MATCHMAKING_PRO_CLUB = 1;
    public static int DROPOUT_EVENT_MATCHMAKING_PRO_CLUB = 1;
    

    // === TOTALE EVENTI PER BLOCCO ===
    public static int ALL_EVENTS_LOGIN = ARRIVAL_EVENT_LOGIN + SERVERS_LOGIN + DROPOUT_EVENT_LOGIN;
    public static int ALL_EVENTS_ULTIMATE_TEAM = ARRIVAL_EVENT_ULTIMATE_TEAM + SERVERS_ULTIMATE_TEAM + DROPOUT_EVENT_ULTIMATE_TEAM;
    public static int ALL_EVENTS_STAGIONI = ARRIVAL_EVENT_STAGIONI + SERVERS_STAGIONI + DROPOUT_EVENT_STAGIONI;
    public static int ALL_EVENTS_PRO_CLUB = ARRIVAL_EVENT_PRO_CLUB + SERVERS_PRO_CLUB + DROPOUT_EVENT_PRO_CLUB;
    public static int ALL_EVENTS_MATCHMAKING_UT = ARRIVAL_EVENT_MATCHMAKING_UT + SERVERS_MATCHMAKING_UT + DROPOUT_EVENT_MATCHMAKING_UT;
    public static int ALL_EVENTS_MATCHMAKING_STAGIONI = ARRIVAL_EVENT_MATCHMAKING_STAGIONI + SERVERS_MATCHMAKING_STAGIONI + DROPOUT_EVENT_MATCHMAKING_STAGIONI;
    public static int ALL_EVENTS_MATCHMAKING_PRO_CLUB = ARRIVAL_EVENT_MATCHMAKING_PRO_CLUB + SERVERS_MATCHMAKING_PRO_CLUB + DROPOUT_EVENT_MATCHMAKING_PRO_CLUB;

 }
